general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follows_focus: false

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: true

  # Whether to show floating windows as always on top.
  show_floating_on_top: false

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # Whether to center new floating windows.
  center_new_floating_windows: true

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "unchanged"

gaps:
  # Gap between adjacent windows.
  inner_gap: "3px"

  # Gap between windows and the screen edge.
  outer_gap: '40px 5px 5px 5px'
  # outer_gap: "5px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#01922C"

  inactive:
    enabled: false
    color: "#0f0f0f"

bar:
  enabled: false
  height: "27px"
  position: "top"
  opacity: 1.0
  background: "ffffff"
  # background: "#20242cd4"
  foreground: "#00CC6A"
  font_family: "CaskaydiaCove Nerd Font"
  font_size: "13px"
  font_weight: "500"
  padding: "4px 6px"
  offset_x: "8px"
  offset_y: "6px"
  # border_width: "1"
  # border_color: "#01922C"
  # border_radius: "8px"
  always_on_top: false
  components_left:
    - type: "text"
      border_width: "1"
      border_color: "#01922C"
      border_radius: "8px"
      background: "#20242cd4"
      background_radius: "8px"
      text: "   " # windows icon
      font_weight: "700"
      font_size: "14px"
      foreground: "#3A86FF"
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      background: "#ffffff33"
      margin: "0 2px"
      padding: "0 5px"
    - type: "workspaces"
      focused_workspace_background: "#5654a2"
      displayed_workspace_background: "#21262d"
      default_workspace_background: "transparent"
  components_center:
    - type: "window title"
      width: "1px"
  components_right:
    - type: "binding mode"
      background: "#ffffff33"
      margin: "0 4px 0 0"
      padding: "0 8px"
    - type: "weather"
      latitude: 50.02994
      longitude: 21.98734
      label: "{temperature_celsius}°C "
      label_sun: "☀️{temperature_celsius}°C "
      label_moon: "🌙 {temperature_celsius}°C "
      label_cloud_moon: "🌙☁️ {temperature_celsius}°C "
      label_cloud_sun: "⛅ {temperature_celsius}°C "
      label_cloud_moon_rain: "🌙🌧️ {temperature_celsius}°C "
      label_cloud_sun_rain: "🌦️ {temperature_celsius}°C "
      label_cloud_rain: "🌧️ {temperature_celsius}°C "
      label_snow_flake: "❄️ {temperature_celsius}°C "
      label_thunderstorm: "⚡ {temperature_celsius}°C "
      label_cloud: "☁️ {temperature_celsius}°C "
    - type: "cpu"
      label: "<attr fs='15' fg='#7ce38b'> </attr>{percent_usage}% "
      refresh_interval_ms: 2000
    - type: "memory"
      label: "<attr fs='15' fg='#7ce38b'> </attr>{percent_usage}% "
      refresh_interval_ms: 3000
    # - type: "gpu"
    #   label: "<attr fs='15' fg='#7ce38b'>󱝊 </attr>{percent_usage}%"
    #   margin: "0px 10px 0px 0px"
    #   refresh_interval_ms: 3000
    - type: "volume"
      label: "<attr fs='16' fg='#7ce38b'></attr>{volume_level}%"
      padding: "0 2px"
      label_low: "<attr fs='16' fg='#7ce38b'></attr>{volume_level}%"
      label_medium: "<attr fs='16' fg='#7ce38b'></attr>{volume_level}%"
      label_high: "<attr fs='14' fg='#7ce38b'></attr>{volume_level}%"
      label_mute: "<attr fs='16' fg='#7ce38b'></attr>{volume_level}%"
    - type: "battery"
      label_draining: "<attr fs='16' fg='#7ce38b'>󰂁</attr>{battery_level}%"
      label_power_saver: "<attr fs='16' fg='#7ce38b'>󱈏</attr>{battery_level}%"
      label_charging: "<attr fs='16' fg='#7ce38b'>󰂄</attr>{battery_level}%"
      margin: "0 8px"
    - type: "network"
      label_no_internet: "NC"
      label_ethernet: "Eth"
      label_wifi_strength_0: "WiFi: 0%"
      label_wifi_strength_25: "WiFi: 25%"
      label_wifi_strength_50: "WiFi: 50%"
      label_wifi_strength_75: "WiFi: 75%"
      label_wifi_strength_100: "WiFi: 100%"
    - type: "clock"
      # Documentation on formatting date/time string:
      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      foreground: "#ead89a"
      font_weight: "700"
      # time_formatting: "hh:mm:ss tt  ddd MMM d"
      time_formatting: " H:mm  ddd d MMM"


# my bar
# bar:
#   height: "0px"
#   position: "top"
#   opacity: 1.0
#   background: "#20242cd4"
#   foreground: "#00CC6A "
#   font_family: "Segoe UI"
#   font_size: "14px"

  # padding: "4px 6px"
  # offset_x: "8"
  # offset_y: "5"
  # border_radius: "8px"
  # border_color: "#01922C"
  # border_width: "1"
  # components_left:
  #   - type: "system tray"
  #   - type: "cpu"
  #     label: "CPU: {percent_usage}%"
  #     margin: "0px 10px 0px 0px"
  #     refresh_interval_ms: 1000
  #   - type: "gpu"
  #     label: "<attr fs='20' fg='#7ce38b'>󱝊</attr>{percent_usage}%"
  #     margin: "0px 10px 0px 0px"
  #     refresh_interval_ms: 1000
  #   - type: "memory"
  #     label: "<attr fs='20' fg='#7ce38b'></attr>{percent_usage}%"
  #     margin: "0px 10px 0px 0px"
  #     refresh_interval_ms: 1000
  # components_center:
  #   - type: "workspaces"
  #     focused_workspace_background: "#ffffff33"
  #     displayed_workspace_background: "#00000033"
  #     default_workspace_background: "transparent"
  #   - type: "window title"
  # components_right:
  #   - type: "tiling direction"
  #     label_horizontal: "⮂"
  #     label_vertical: "⮁"
  #     background: "#ffffff33"
  #     margin: "0 4px"
  #     padding: "0 8px"
  #   - type: "binding mode"
  #     background: "#ffffff33"
  #     margin: "0 4px 0 0"
  #     padding: "0 8px"
  #   - type: "cpu"
  #     label: "CPU: {percent_usage}% "
  #     refresh_interval_ms: 1000
  #   - type: "battery"
  #     draining: "{battery_level}% 🔋 remaining"
  #     power_saver: "{battery_level}% 🔁 (power saver)"
  #     charging: "{battery_level}% ⚡ (charging)"
  #   - type: "clock"
  #     # Documentation on formatting date/time string:
  #     # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
  #     time_formatting: "hh:mm tt  ddd MMM d"

workspaces:
  - name: "1"
  - name: "2"
    bind_to_monitor: "5"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  # Ignore the bar window.
  - command: 'ignore'
    match_process_name: '/Zebar/'
  - command: "move to workspace 3"
    match_process_name: "brave"
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  - commands: ["set floating", "move up", "move up", "move up", "move up", "move up", "move up", "move up", "move right", "move right", "move right", "move right"]
    match_class_name: "XamlWindow"

  # Do not manage picture-in-picture windows for browsers. Note that the default is for
  # English; change `match_title` to the window's title if you use another language.
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["K", "Up"]
      - command: "resize height -2%"
        bindings: ["J", "Down"]
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+H", "Alt+Left"]
  - command: "focus right"
    bindings: ["Alt+L", "Alt+Right"]
  - command: "focus up"
    bindings: ["Alt+K", "Alt+Up"]
  - command: "focus down"
    bindings: ["Alt+J", "Alt+Down"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["Alt+Shift+H", "Alt+Shift+Left"]
  - command: "move right"
    bindings: ["Alt+Shift+L", "Alt+Shift+Right"]
  - command: "move up"
    bindings: ["Alt+Shift+K", "Alt+Shift+Up"]
  - command: "move down"
    bindings: ["Alt+Shift+J", "Alt+Shift+Down"]

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+P"
  - command: "resize height +2%"
    binding: "Alt+O"
  - command: "resize height -2%"
    binding: "Alt+I"

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "Alt+R"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "Alt+V"

  # Change focus between floating / tiling windows.
  - command: "focus mode toggle"
    binding: "Alt+Space"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "Alt+Shift+Space"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "Alt+X"

  # Minimize focused window.
  - command: "set minimized"
    binding: "Alt+M"

  # Close focused window.
  - command: "close"
    binding: "Alt+Shift+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "Alt+Shift+E"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "Alt+Shift+R"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec cmd"
    binding: "Alt+Enter"

  - command: "exec 'C:/Program Files/SystemInformer/SystemInformer.exe'"
    binding: "Alt+OemQuotes"

  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "Alt+Y"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+T"
  - command: "focus workspace prev"
    binding: "Alt+Shift+T"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"

  # Move focused workspace to a monitor in a given direction.
  - command: "move workspace left"
    binding: "Alt+A"
  - command: "move workspace right"
    binding: "Alt+F"
  - command: "move workspace up"
    binding: "Alt+D"
  - command: "move workspace down"
    binding: "Alt+S"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+9"]
