# Yaml is white-space sensitive (use 2 spaces to indent).

###
# Settings to apply to all windows.
#
# Docs regarding global: https://some-future-docs-link.com
global:
  # Whether to enable the browser devtools.
  enable_devtools: true

###
# Define a new window with an id of 'bar'. This window can then be opened
# via the Zebar cli by running 'zebar open bar'.
#
# Docs regarding window: https://some-future-docs-link.com
window/bar:
  providers:
  - type: 'self'
  - type: 'date'

  # Width of the window in physical pixels.
  width: '{{ self.args.MONITOR_WIDTH }}'
  # Height of the window in physical pixels.
  height: '35'
  # X-position of the window in physical pixels.
  position_x: '{{ self.args.MONITOR_X }}'
  # Y-position of the window in physical pixels.
  position_y: '{{ self.args.MONITOR_Y }}'
  # Whether to show the window above/below all others.
  # Allowed values: 'always_on_top', 'always_on_bottom', 'normal'.
  z_order: 'always_on_bottom'
  # Whether the window should be shown in the taskbar.
  show_in_taskbar: false
  # Whether the window should have resize handles.
  resizable: false
  # Styles to apply globally within the window. For example, we can use
  # this to import the Nerdfonts icon font. Ref https://www.nerdfonts.com/cheat-sheet
  # for a cheatsheet of available Nerdfonts icons.
  global_styles: |
    @import "https://www.nerdfonts.com/assets/css/webfont.css";
  # CSS/SCSS styles to apply to the root element within the window.
  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    color: #ffffffe6;
    font-family: CaskaydiaCove Nerd Font, ui-monospace, monospace;
    font-size: 13px;
    # border-bottom: 1px solid white;
    # background: #1c1c1cea;
    .group {
      padding-top: 3px;
      margin: 0 0 5px 0;
    }
    span {
      display: flex;
      align-items: center;
    }
    .medium-usage {
      color: #D1DF4A;
    }
    .high-usage {
      color: #FB8C00;
    }
    .extreme-usage {
      color: #ff3e3e;
    }
    .i {
      margin-right: 7px;
      font-size: 15px;
    }
    .template {
      display: flex;
      align-items: center;
      user-select: none;
      height: 100%;
    }
    button {
      display: flex;
      align-items: center;
      text-shadow: 0 0 2px black;
      margin: 0 1px 0 0;
      height: 22px;
      color: #ffffff;
      border: 1px solid transparent;
      background: none;
      border-radius: 4px;
    }
    button:hover {
      border: 1px solid #00000005;
      background: #aeaeae33;
      box-shadow: 0 -1px 1px #9e9e9e44,
                  0 1px 1px #24242455;
    }

  group/left:
    styles: |
      display: flex;
      align-items: center;
      flex-direction: row;
      justify-content: left;
      padding-left: 2px;
      i {
        margin-right: 4px;
        # margin-left: 0;
      }
      .i {
        font-size: 15px;
      }
    template/logo:
      styles: |
        .workspace{
          color: #3A86FF;
          padding-left: 5px;
          font-size: 15px;
          width: 25px;
        }
      template: |
        <!-- Windows Logo -->
        <button class="workspace"></button>
    
    template/cpu:
      providers:
      - type: 'cpu'
        refresh_interval: 2000
      styles: |
        button{
          color: #00CC6A;
        }
        .i {
          font-size: 17px;
        }
      template: |
        <!-- Change the text color if the CPU usage is high. -->
        <button>
        @if (cpu.usage > 90) {
          <button class="extreme-usage"><span class="i">󰻠</span>{{ Math.round(cpu.usage) }}%</button>
        } @else if (cpu.usage > 65) {
          <span class="high-usage"><span class="i">󰻠</span>{{ Math.round(cpu.usage) }}%</span>
        } @else if (cpu.usage > 35) {
          <span class="medium-usage"><span class="i">󰻠</span>{{ Math.round(cpu.usage) }}%</span>
        } @else {
          <span><span class="i">󰻠</span>{{ Math.round(cpu.usage) }}%</span>
        }
        </button>

    template/memory:
      providers:
      - type: 'memory'
        refresh_interval: 3000
      styles: |
        button{
          color: #00CC6A;
        }
        .i {
          margin-right: 9px;
        }
      template: |
        <button>
        @if (memory.usage > 90) {
          <span class="extreme-usage"><span class="i"></span>{{ Math.round(memory.usage) }}%</span>
        } @else if (memory.usage > 65) {
          <span class="high-usage"><span class="i"></span>{{ Math.round(memory.usage) }}%</span>
        } @else if (memory.usage > 50) {
          <span class="medium-usage"><span class="i"></span>{{ Math.round(memory.usage) }}%</span>
        } @else {<span class="i"></span>{{ Math.round(memory.usage) }}%}
        </button>
    template/weather:
      providers:
      - type: 'weather'
        latitude: 50.02994
        longitude: 21.98734
      styles: |
        button{
          color: #DCE775;
        }
      template: |
        <button>
        @switch (weather.status) {
          @case ('clear_day') {<i class="nf nf-weather-day_sunny"></i>}
          @case ('clear_night') {<i class="nf nf-weather-night_clear"></i>}
          @case ('cloudy_day') {<i class="nf nf-weather-day_cloudy"></i>}
          @case ('cloudy_night') {<i class="nf nf-weather-night_alt_cloudy"></i>}
          @case ('light_rain_day') {<i class="nf nf-weather-day_sprinkle"></i>}
          @case ('light_rain_night') {<i class="nf nf-weather-night_alt_sprinkle"></i>}
          @case ('heavy_rain_day') {<i class="nf nf-weather-day_rain"></i>}
          @case ('heavy_rain_night') {<i class="nf nf-weather-night_alt_rain"></i>}
          @case ('snow_day') {<i class="nf nf-weather-day_snow"></i>}
          @case ('snow_night') {<i class="nf nf-weather-night_alt_snow"></i>}
          @case ('thunder_day') {<i class="nf nf-weather-day_lightning"></i>}
          @case ('thunder_night') {<i class="nf nf-weather-night_alt_lightning"></i>}
        }
        {{ Math.round(weather.celsiusTemp) }}°C
        </button>
  group/center:
    styles: |
      justify-self: center;
    template/glazewm:
      styles: |
        display: flex;
        align-items: center;
        .workspace {
          width: 22px;
        }

      providers: ['glazewm']
      template: |
        @for (workspace of glazewm.workspacesOnMonitor) {
          <button class="workspace">{{ workspace.name }}</button>
        }

  group/right:
    styles: |
      display: flex;
      align-items: center;
      flex-direction: row;
      justify-self: end;
      .i {
        margin-right: 7px;
        font-size: 15px;
      }
    template/battery:
      providers:
      - type: 'battery'
        refresh_interval: 10000
      styles: |
        button{
          position: relative;
          color: #00CC6A;
        }
        .charging-icon {
          color: #fdc93e;
          position: absolute;
          font-size: 11px;
          left: 11px;
          top: 5px;
          z-index: 99;
        }
        .i {
          margin-right: 11px;
        }
      template: |
        <!-- Show icon for whether battery is charging. -->
        <button>
        @if (battery.isCharging) {<span class="charging-icon">⚡</span>}

        <!-- Show icon for how much of the battery is charged. -->
        @if (battery.chargePercent > 90) {<span class="i"></span>}
        @else if (battery.chargePercent > 70) {<span class="i"></span>}
        @else if (battery.chargePercent > 40) {<span class="i"></span>}
        @else if (battery.chargePercent > 20) {<span class="i"></span>}
        @else {<span class="i"></span>}

        {{ Math.round(battery.chargePercent) }}%
        </button>
    template/clock:
      # Available date tokens: https://moment.github.io/luxon/#/formatting?id=table-of-tokens
      styles: |
        button{
          color: #82def9;
        }
      template: |
        <button>
        {{ date.toFormat(date.now, 'H:mm') }}
        <span style="color: #ede296; margin-left: 8px;"> {{ date.toFormat(date.now, ' d/MM/yy') }}</span>
        </button>

window/cpuinfo:
